### ISSUE TITLE
2.11.0 uses unreleased flint symbols

### ISSUE THREAD

**Issue by ilovezfs** [fredrik-johansson/arb#189]
See https://www.mail-archive.com/arch-commits@archlinux.org/msg342324.html

with the proposed patch
```
diff --git a/arb_fmpz_poly/gauss_period_minpoly.c b/arb_fmpz_poly/gauss_period_minpoly.c
index 3ce304aa..2fba47ea 100644
--- a/arb_fmpz_poly/gauss_period_minpoly.c
+++ b/arb_fmpz_poly/gauss_period_minpoly.c
@@ -87,7 +87,7 @@ arb_fmpz_poly_gauss_period_minpoly(fmpz_poly_t res, ulong q, ulong n)
             {
                 for (e = 0; e < d / 2; e++)
                 {
-                    acb_dirichlet_root(t, zeta, n_mulmod2(gk, es[e], 2 * q), prec);
+                    acb_dirichlet_root(t, zeta, n_mulmod2_preinv(gk, es[e], 2 * q, n_preinvert_limb(2 * q)), prec);
                     acb_mul_2exp_si(t, t, 1);  /* compute conjugates */
                     acb_add(u, u, t, prec);
                 }
@@ -98,7 +98,7 @@ arb_fmpz_poly_gauss_period_minpoly(fmpz_poly_t res, ulong q, ulong n)
             {
                 for (e = 0; e < d; e++)
                 {
-                    acb_dirichlet_root(t, zeta, n_mulmod2(gk, es[e], 2 * q), prec);
+                    acb_dirichlet_root(t, zeta, n_mulmod2_preinv(gk, es[e], 2 * q, n_preinvert_limb(2 * q)), prec);
                     acb_add(u, u, t, prec);
                 }
```

Fixes
```
    CC   ../build/arb_fmpz_poly/gauss_period_minpoly.lo
    CC   ../build/arb_fmpz_poly/inlines.lo
    CC   ../build/arb_fmpz_poly/../arb_fmpz_poly.lo
Undefined symbols for architecture x86_64:
  "_n_mulmod2", referenced from:
      _arb_fmpz_poly_gauss_period_minpoly in arb_fmpz_poly.lo
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libarb-2.2.0.dylib] Error 1
make: *** [library] Error 2
```

See https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/876/version=sierra/console

**Comment by ilovezfs** [comment]
CC @fredrik-johansson @antonio-rojas

**Comment by fredrik-johansson** [comment]
Argh! I'm afraid we were testing against flint-trunk instead of 2.5 on Travis. I have pushed a fix and will tag 2.11.1 as soon as the tests complete.

**Comment by ilovezfs** [comment]
@fredrik-johansson hehe Thanks!

**Comment by ilovezfs** [comment]
@fredrik-johansson still getting a failure in the tests, testing HEAD:
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/878/version=sierra/console
```
PASS
PASS
    CC   ../build/dlog/test/t-dlog
    CC   ../build/dlog/test/t-modpe
    CC   ../build/dlog/test/t-vec
dlog....modpe....vec....PASS
PASS
PASS
    CC   ../build/arb_fmpz_poly/test/t-complex_roots
    CC   ../build/arb_fmpz_poly/test/t-evaluate_acb
    CC   ../build/arb_fmpz_poly/test/t-evaluate_arb
    CC   ../build/arb_fmpz_poly/test/t-gauss_period_minpoly
evaluate_arb....evaluate_acb....Undefined symbols for architecture x86_64:
  "_n_mulmod2", referenced from:
      _main in t-gauss_period_minpoly-fe0ed8.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../build/arb_fmpz_poly/test/t-gauss_period_minpoly] Error 1
make[1]: *** Waiting for unfinished jobs....
PASS
PASS
make: *** [check] Error 2
```

**Comment by fredrik-johansson** [comment]
One more attempt...

**Comment by ilovezfs** [comment]
@fredrik-johansson looks good now: https://github.com/Homebrew/homebrew-science/pull/5950

**Comment by ilovezfs** [comment]
@fredrik-johansson Thanks for the speedy fix! I've updated https://github.com/Homebrew/homebrew-science/pull/5950 to be for 2.11.1
